# Site settings
author: Chris Ortman
title: Chris Ortman
email: chrisortman@gmail.com
description: "Personal web site for chris ortman"
baseurl: ""
url: "http://chrisortman.com"
gravatar_url: http://www.gravatar.com/avatar/d57d8b027fe943f061b6187d870443a7
timezone:    America/Chicago

# Github repositories
github_username: chrisortman
github_repo_url: https://github.com/chrisortman/chrisortman.github.com/

# Twitter
twitter_username: chriso
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: chrisoblog
disqus_show_comment_count: true

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["tables"]
permalink: pretty


